// components/Navbar.vue

<template>
  <div>
    <nav class="relative dark:bg-dark bg-white px-6 py-4">
      <div class="lg:flex lg:items-center lg:justify-between container mx-auto">
        <div class="flex items-center justify-between">
          <NuxtLink to="/" class="transition-colors duration-300 transform w-32 h-12">
            <h2 class="logo text-balticSea dark:text-lavenderMist font-semibold whitespace-nowrap">School Finder App
            </h2>
          </NuxtLink>

          <!-- Mobile menu button -->
          <div class="flex lg:hidden">
            <button @click="isOpen = !isOpen" type="button"
              class="text-gray-500 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400 focus:outline-none focus:text-gray-600 dark:focus:text-gray-400"
              aria-label="toggle menu">
              <svg v-show="!isOpen" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
                stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 8h16M4 16h16" />
              </svg>

              <svg v-show="isOpen" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
                stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
        <div :class="isOpen ? 'translate-x-0 opacity-100' : 'opacity-0 -translate-x-full'"
          class="absolute inset-x-0 z-20 w-full grow-[0.5] justify-between px-6 py-4 transition-all duration-300 ease-in-out lg:mt-0 lg:bg-transparent lg:dark:bg-transparent bg-white dark:bg-gray-800 lg:p-0 lg:top-0 lg:relative lg:w-auto lg:opacity-100 lg:translate-x-0 lg:flex lg:items-center">
          <div class="flex flex-col -mx-6 lg:flex-row lg:items-center lg:mx-8">
            <NuxtLink :to="navLink.href" v-for="navLink, index in NavbarLink" :key="index"
              class="pr-3 py-2 mx-3 mt-2 lg:w-full w-fit whitespace-nowrap hover:border-b-4 hover:border-b-sky-700 text-gray-700 transition-colors duration-300 transform lg:mt-0 dark:text-gray-200">
              {{ navLink.name}}</NuxtLink>
          </div>

          <div class="flex items-center mt-4 lg:mt-0">
            <button @click="setColorTheme($colorMode.preference == 'dark' ? 'light' : 'dark')">
              <template v-if="$colorMode.value == 'dark'">
                <img src="/assets/icons/lightMode.svg" class="w-8 h-8" alt="lightMode">
              </template>
              <template v-else>
                <img src="/assets/icons/darkMode.png" class="w-8 h-8" alt="darkMode">
              </template>
            </button>
            <button
              class="hidden mx-4 text-gray-600 transition-colors duration-300 transform lg:block dark:text-gray-200 hover:text-gray-700 dark:hover:text-gray-400 focus:text-gray-700 dark:focus:text-gray-400 focus:outline-none"
              aria-label="show notifications">
              <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M15 17H20L18.5951 15.5951C18.2141 15.2141 18 14.6973 18 14.1585V11C18 8.38757 16.3304 6.16509 14 5.34142V5C14 3.89543 13.1046 3 12 3C10.8954 3 10 3.89543 10 5V5.34142C7.66962 6.16509 6 8.38757 6 11V14.1585C6 14.6973 5.78595 15.2141 5.40493 15.5951L4 17H9M15 17V18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18V17M15 17H9"
                  stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </button>

            <button type="button" class="flex items-center focus:outline-none" aria-label="toggle profile dropdown">
              <div class="w-8 h-8 overflow-hidden border-2 border-gray-400 rounded-full">
                <img
                  src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80"
                  class="object-cover w-full h-full" alt="avatar">
              </div>
              <h3 class="mx-2 text-gray-700 dark:text-gray-200 lg:hidden">Khatab wedaa</h3>
            </button>
          </div>
        </div>
      </div>
    </nav>
  </div>
</template>
<script setup lang="ts">
const isOpen = ref(false)
type Theme = 'light' | 'dark';
const setColorTheme = (newTheme: Theme) => {
  useColorMode().preference = newTheme
}

const NavbarLink = [
  {
    name: 'Home',
    href: '/',

  },
  {
    name: 'About',
    href: '/about',

  },
]

</script>

// components/Navbar.jsx
import Link from "next/link";
import { useState } from "react";
import Image from "next/image";
import burgerMenuIcon from "/public/burger-menu.svg";
import cancelIcon from "/public/x-mark.svg";
import { useSession, signOut } from "next-auth/react"
import DropDown from "./DropDown";

const Navbar = () => {
	const [isOpen, setIsOpen] = useState(false);
	const session = useSession();
	let mobileNavDynamicClass =
		"lg:relative transition-opacity lg:opacity-100 ease-linear duration-300 absolute left-0 lg:mt-0 mt-2 w-full lg:w-auto bg-almond bg-opacity-95 lg:bg-transparent ";
	if (isOpen) {
		mobileNavDynamicClass += "lg:opacity-100 opacity-100 lg:block block";
	} else {
		mobileNavDynamicClass += "lg:opacity-100 opacity-0 lg:block hidden";
	}

	const navLink = [
		{
			page: "Home",
			link: "/",
		},
		{
			page: "About",
			link: "/about",
		},
		{
			page: "Our Schools",
			link: "/our-schools",
		},
		{
			page: "Contact",
			link: "/contact",
		},
		{
			page: "Profile",
			link: "/profile",
		},
	];
	return (
		<>
			<nav className='bg-almond bg-opacity-95 z-30 sticky top-0 left-0 right-0'>
				<div className='px-6 py-2 lg:flex lg:items-center lg:justify-between max-w-7xl lg:mx-auto'>
					<div className='flex justify-between items-center'>
						<Link href={"/"} className='cursor-pointer'>
							<Image
								className='w-40 h-auto inline cursor-pointer'
								width={160}
								height={65.27}
								src='/images/logo.svg'
								alt='logo'
							/>
						</Link>
						<span
							className='text-3xl cursor-pointer mx-2 lg:hidden block'
							onClick={() => setIsOpen(!isOpen)}>
							{!isOpen ? (
								<Image src={burgerMenuIcon} width={24} height={24} alt="burger-menu" />

							) : (
								<Image src={cancelIcon} width={24} height={24} alt="cancelIcon" />
							)}
						</span>
					</div>
					<div className={mobileNavDynamicClass}>
						<div className='flex lg:flex-row flex-col gap-x-14 gap-y-5 lg:py-0 py-4 lg:px-0 px-6'>
							<div className='flex lg:items-center items-start lg:flex-row flex-col gap-5'>
								{navLink.map((item, index) => {
									return (
										<Link
											key={index}
											href={item.link}
											className='whitespace-nowrap font-medium text-base text-black  hover:text-rustyRed'>
											{item.page}
										</Link>
									);
								})}
							</div>
							<div className='flex items-center gap-3'>
								{
									(session?.data?.user) ? (
										<DropDown>
											<div class="relative">
												<img class="object-cover w-12 h-12 rounded-full" src={session?.data?.user?.image} alt="user-image" />
												<span class="absolute bottom-0 w-2 h-2 rounded-full bg-green-500 right-1 ring-1 ring-white"></span>
											</div>
											<>
												<span className="block px-4 py-3 text-sm font-bold text-gray-600 capitalize">{session?.data?.user?.name}	</span>
												<button className="block px-4 py-3 text-sm text-gray-600 capitalize" onClick={() => signOut()}>
													logout
												</button>
											</>
										</DropDown>
									) : (
										<Link
											href={'/signin'}
											className='cursor-pointer text-base font-semibold border border-black px-7 py-2 rounded-full text-black transition-all duration-200 hover:text-opacity-80'>
											Login
										</Link>
									)
								}
							</div>

						</div>
					</div>
				</div>
			</nav>
		</>
	);
};

export default Navbar;
